added tsunami directory
clawpack/seismic pull request #9
Opened 2016-09-10 18:09 UTC by rjleveque

with some sample code to run a 1d geoclaw model with piecewise linear topo.

See the README files in this directory and subdirectories.

2016-09-16 19:34 UTC, cjvogl commented on tsunami/1d/pwlinear1/setrun.py
> +import clawpack.geoclaw.shallow_1d.data as geoclaw1d
Getting an error that this shallow_1d.data is not found... is there a branch of geoclaw that is needed for this?

2016-09-16 19:34 UTC, cjvogl requested changes

2016-09-17 00:15 UTC, cjvogl approved these changes

2016-12-20 18:25 UTC, rjleveque commented
@cjvogl I added a commit adding a scale_longitude attribute so the Okada model works more consistently on subdivided faults in the 1d case where units are meters rather than longitude.

I looks like many other changes on this branch didn't get merged into master.  You can do so if it doesn't conflict with your work.

2016-12-21 06:59 UTC, merged